version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: smartdiagnosis_postgres
    restart: always
    environment:
      POSTGRES_DB: smartdiagnosis_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

