"""initial schema

Revision ID: 40e7f91313aa
Revises: 
Create Date: 2026-03-03 19:05:57.474911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e7f91313aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('document_type', sa.String(length=10), nullable=False),
    sa.Column('document_number', sa.String(length=32), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_created_by'), 'patients', ['created_by'], unique=False)
    op.create_index('ix_patients_full_name', 'patients', ['full_name'], unique=False)
    op.create_index('uq_patients_doc', 'patients', ['created_by', 'document_type', 'document_number'], unique=True)
    op.create_table('clinical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('blood_glucose_level', sa.Float(), nullable=False),
    sa.Column('hba1c_level', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('systolic_bp', sa.Float(), nullable=False),
    sa.Column('diastolic_bp', sa.Float(), nullable=False),
    sa.Column('heart_disease', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_records_created_by'), 'clinical_records', ['created_by'], unique=False)
    op.create_index('ix_clinical_records_patient_created', 'clinical_records', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_clinical_records_patient_id'), 'clinical_records', ['patient_id'], unique=False)
    op.create_index('ix_clinical_records_patient_recorded', 'clinical_records', ['patient_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_clinical_records_recorded_at'), 'clinical_records', ['recorded_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('clinical_record_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('predicted_label', sa.Integer(), nullable=False),
    sa.Column('predicted_proba', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinical_record_id'], ['clinical_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_clinical_record_id'), 'predictions', ['clinical_record_id'], unique=False)
    op.create_index(op.f('ix_predictions_created_by'), 'predictions', ['created_by'], unique=False)
    op.create_index('ix_predictions_patient_created', 'predictions', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_predictions_patient_id'), 'predictions', ['patient_id'], unique=False)
    op.create_index('ix_predictions_record_created', 'predictions', ['clinical_record_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_predictions_record_created', table_name='predictions')
    op.drop_index(op.f('ix_predictions_patient_id'), table_name='predictions')
    op.drop_index('ix_predictions_patient_created', table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_by'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_clinical_record_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_clinical_records_recorded_at'), table_name='clinical_records')
    op.drop_index('ix_clinical_records_patient_recorded', table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_patient_id'), table_name='clinical_records')
    op.drop_index('ix_clinical_records_patient_created', table_name='clinical_records')
    op.drop_index(op.f('ix_clinical_records_created_by'), table_name='clinical_records')
    op.drop_table('clinical_records')
    op.drop_index('uq_patients_doc', table_name='patients')
    op.drop_index('ix_patients_full_name', table_name='patients')
    op.drop_index(op.f('ix_patients_created_by'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
