"""create patients and clinical_records

Revision ID: 756fdf2e2195
Revises: 09005e2a7e10
Create Date: 2026-02-10 13:03:58.985559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756fdf2e2195'
down_revision: Union[str, Sequence[str], None] = '09005e2a7e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clinical_records_patient_created', 'clinical_records', ['patient_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_clinical_records_patient_id'), 'clinical_records', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_records_patient_id'), table_name='clinical_records')
    op.drop_index('ix_clinical_records_patient_created', table_name='clinical_records')
    op.drop_table('clinical_records')
    # ### end Alembic commands ###
