"""create patients table

Revision ID: 94c3cd41d476
Revises: 
Create Date: 2026-02-10 12:43:49.412152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c3cd41d476'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('document_type', sa.String(length=10), nullable=False))
    op.add_column('patients', sa.Column('document_number', sa.String(length=32), nullable=False))
    op.add_column('patients', sa.Column('birth_date', sa.Date(), nullable=False))
    op.alter_column('patients', 'full_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=120),
               existing_nullable=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.create_index('ix_patients_full_name', 'patients', ['full_name'], unique=False)
    op.create_index('uq_patients_doc', 'patients', ['document_type', 'document_number'], unique=True)
    op.drop_constraint(op.f('patients_user_id_fkey'), 'patients', type_='foreignkey')
    op.drop_column('patients', 'date_of_birth')
    op.drop_column('patients', 'user_id')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('patients', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('patients_user_id_fkey'), 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index('uq_patients_doc', table_name='patients')
    op.drop_index('ix_patients_full_name', table_name='patients')
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('patients', 'full_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('patients', 'birth_date')
    op.drop_column('patients', 'document_number')
    op.drop_column('patients', 'document_type')
    # ### end Alembic commands ###
